//the file is generated by python script, DO NOT EDIT


#ifndef MACHO_MAPPING
#define MACHO_MAPPING
#include <map>
#include <string>


std::map<uint32_t, std::string> macho_mapping;

int init(){
    macho_mapping[0x1]		=	std::string("MH_NOUNDEFS");
    macho_mapping[0x2]		=	std::string("MH_INCRLINK");
    macho_mapping[0x4]		=	std::string("MH_DYLDLINK");
    macho_mapping[0x8]		=	std::string("MH_BINDATLOAD");
    macho_mapping[0x10]		=	std::string("MH_PREBOUND");
    macho_mapping[0x20]		=	std::string("MH_SPLIT_SEGS");
    macho_mapping[0x40]		=	std::string("MH_LAZY_INIT");
    macho_mapping[0x80]		=	std::string("MH_TWOLEVEL");
    macho_mapping[0x100]		=	std::string("MH_FORCE_FLAT");
    macho_mapping[0x200]		=	std::string("MH_NOMULTIDEFS");
    macho_mapping[0x400]		=	std::string("MH_NOFIXPREBINDING");
    macho_mapping[0x800]		=	std::string("MH_PREBINDABLE");
    macho_mapping[0x1000]		=	std::string("MH_ALLMODSBOUND");
    macho_mapping[0x2000]		=	std::string("MH_SUBSECTIONS_VIA_SYMBOLS");
    macho_mapping[0x4000]		=	std::string("MH_CANONICAL");
    macho_mapping[0x8000]		=	std::string("MH_WEAK_DEFINES");
    macho_mapping[0x10000]		=	std::string("MH_BINDS_TO_WEAK");
    macho_mapping[0x20000]		=	std::string("MH_ALLOW_STACK_EXECUTION");
    macho_mapping[0x40000]		=	std::string("MH_ROOT_SAFE");
    macho_mapping[0x80000]		=	std::string("MH_SETUID_SAFE");
    macho_mapping[0x100000]		=	std::string("MH_NO_REEXPORTED_DYLIBS");
    macho_mapping[0x200000]		=	std::string("MH_PIE");
    macho_mapping[0x400000]		=	std::string("MH_DEAD_STRIPPABLE_DYLIB");
    macho_mapping[0x800000]		=	std::string("MH_HAS_TLV_DESCRIPTORS");
    macho_mapping[0x1000000]		=	std::string("MH_NO_HEAP_EXECUTION");
    macho_mapping[0x02000000]		=	std::string("MH_APP_EXTENSION_SAFE");

    return 0;
}

#endif